### ISSUE TITLE
Update website to specify that the website only supports human variants.

### ISSUE THREAD

**Issue by tmushayahama** [USCbiostats/annoq-site#15]
We need to update website to specify that the website only supports human variants.
Three places need to be updated. 

- [ ] Home page, under the 39 million, add text "Currently only human variants are supported". 
- [ ] In the Supported Annotation page, add the same text somewhere on the page
- [ ] On the About page, add the same sentence before the last sentence ("The data is built ....")

**Comment by huaiyumi** [comment]
The banner is in the middle of the page.
