### ISSUE TITLE
Add a link to the AnnoQ paper to the AnnoQ website.

### ISSUE THREAD

**Issue by huaiyumi** [USCbiostats/annoq-site#20]
Here is the link to the paper: https://academic.oup.com/nar/article/50/W1/W57/6595265?searchresult=1
Add a "Citation" link maybe just below the "39 million"
Use the text below and put the linkout to the entire title.
Liu Z, Mushayahama T, Queme B,  Ebert D, Muruganujan A, Mills C, Thomas PD, Mi H. (2022) Annotation Query (AnnoQ): an integrated and interactive platform for large-scale genetic variant annotation. Nucleic Acids Research, Volume 50, Issue W1, Pages W57–W65, https://doi.org/10.1093/nar/gkac418

**Comment by mugitty** [comment]
Completed

**Comment by mugitty** [comment]
Done
